name: geo_quiz
description: Geography quizzes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^5.0.0
  flutter_map_geojson: ^1.0.1
  latlong2: ^0.9.0
  point_in_polygon: ^1.0.0
  collection: ^1.17.1
  get_it: ^7.6.0
  package_info_plus: ^4.0.0
  intl: any
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11
  flutter_riverpod: ^2.3.6
  go_router: ^8.0.0
  riverpod_annotation: ^2.1.1

dev_dependencies:
  build_runner: ^2.4.4
  custom_lint: ^0.4.0
  riverpod_generator: ^2.2.3
  riverpod_lint: ^1.3.2
  total_lints: ^2.19.0 # very strict set of lints
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  flutter_map_geojson:
    git:
      url: https://github.com/josxha/flutter_map_geojson.git
      ref: 164e74e5ee072f527ae6eac85a3b25df9257d7ea

flutter:
  uses-material-design: true
  generate: true # for localization
  assets:
    - assets/countries.json
    - assets/background.jpg
    - assets/flags/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#000000"
    theme_color: "#467012"
  windows:
    generate: true
    image_path: "assets/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
