name: geo_quiz
description: Geography quizzes
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_map_geojson: ^1.0.1
  latlong2: ^0.8.1
  point_in_polygon: ^1.0.0
  collection: ^1.17.1
  get_it: ^7.6.0
  package_info_plus: ^4.0.0
  intl: any
  flutter_svg: ^2.0.5
  font_awesome_flutter: ^10.4.0
  url_launcher: ^6.1.11

dev_dependencies:
  total_lints: ^2.19.0 # very strict set of lints

dependency_overrides:
  flutter_map_geojson:
    path: ../flutter_map_geojson

flutter:
  uses-material-design: true
  generate: true # for localization
  assets:
    - assets/countries.json
    - assets/background.jpg
    - assets/flags/
