name: Build Android
on:
  push:
    branches: [ main ]
jobs:
  build-android:
    runs-on: ubuntu-latest
    name: Build Android
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '19'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - name: Get Flutter dependencies
        run: flutter pub get
      #- run: flutter test
      - name: Build APK
        run: flutter build apk
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-release.apk
      #- run: flutter build appbundle
      #- name: Upload to Firebase App Distribution
      #  uses: wzieba/Firebase-Distribution-Github-Action@v1
      #  with:
      #    appId: ${{secrets.FIREBASE_ANDROID_APP_ID}}
      #    token: ${{secrets.FIREBASE_TOKEN}}
      #    groups: tester
      #    file: build/app/outputs/flutter-apk/app-release.apk
